### ISSUE TITLE
Upload Task Error

### ISSUE THREAD

**Issue by evaleries** [Pemrograman-Fasilkom-Unej/Assistant-Manager#12]
500 Server error saat upload tugas,
Extensi File yg diupload: rar
Response: 500 Server Error
```json
{
    "message": "Server Error"
}
```
![image](https://user-images.githubusercontent.com/48923153/76747088-2bcac900-67ab-11ea-9dca-d7387b4bf01b.png)

[object Object] dikarenakan response json -> diparse jadi object -> di passing di notify. Check line 179. https://github.com/Pemrograman-Fasilkom-Unej/Assistant-Manager/blob/60fb90cdef781d0f58969afde4808cf0f5e50d16/resources/views/home/form.blade.php#L178-L179

**Comment by esdeath11** [comment]
Oh wes di up dida

**Comment by miqdadyyy** [comment]
Done, server udah hidup
