### ISSUE TITLE
BUG Detail Tugas

### ISSUE THREAD

**Issue by dewangga-pk** [Pemrograman-Fasilkom-Unej/Assistant-Manager#18]
![image](https://user-images.githubusercontent.com/55013652/76818502-5878f200-6838-11ea-8922-cdde726f3965.png)

Pas buka detail tugas,error 404

**Comment by miqdadyyy** [comment]
https://github.com/Pemrograman-Fasilkom-Unej/Assistant-Manager/pull/20
