### ISSUE TITLE
Text Limit comment Tugas

### ISSUE THREAD

**Issue by esdeath11** [Pemrograman-Fasilkom-Unej/Assistant-Manager#4]
![Capture](https://user-images.githubusercontent.com/48850021/76183676-d109fe00-61fb-11ea-8cf8-7bb719f1bc28.PNG)
![Issue](https://user-images.githubusercontent.com/48850021/76183679-d1a29480-61fb-11ea-9c43-ce1108cd618d.PNG)

**Comment by miqdadyyy** [comment]
nggeh

**Comment by miqdadyyy** [comment]
https://github.com/Pemrograman-Fasilkom-Unej/Assistant-Manager/commit/b52f65d0c235a743b4a20fc939400e5328d1eb57
